language: elixir
elixir:
  - 1.6.1
otp_release:
  - 20.2
matrix:
  include:
  - otp_release: 18.3
    elixir: 1.4.5
  - otp_release: 19.3
    elixir: 1.5.3
notifications:
  recipients:
    - jose.valim@plataformatec.com.br
    - michal+travis@muskala.eu
